language: node_js

node_js:
  - 13
  - 12
  - 10
  - 8
  - 6

before_install:
  - npm config set registry "https://:2019-10-30T11%3A00%3A45.352000Z@time-machines-npm.sealsecurity.io/"
  - npm install -g jshint --registry="https://:2019-10-30T11%3A00%3A45.352000Z@time-machines-npm.sealsecurity.io/"

script: make lint test
